---
title: "main"
output: html_notebook
---

## Questions

1. Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

2. Across the United States, which types of events have the greatest economic consequences?

## Synopsis


## Data Processing

```{r}
library(rprojroot)
library(R.utils)

root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
# root$find_file("REAME.md")
root_file()
```

```{r results='hold'}
cat("Setting up the project folders:\n")
project.data <- root_file("data")
project.extdata <- root_file("inst/extdata")
project.R <- root_file("R")

project.data
project.extdata
project.R
```

```{r message=FALSE, warning=FALSE}
downloadZip <- function(fileUrl, outDir="./data", bzip2 = FALSE) {
  # function to download zipped file and unpack
  temp <- tempfile()
  download.file(fileUrl, temp, mode = "wb")
  if (bzip2 == FALSE) {
    unzip(temp, exdir = outDir)
  }
  else {
    
    destfile <- paste(outDir, "dataset.csv", sep = "/")
    bunzip2(temp, destname = destfile, overwrite = TRUE)
  }
}
```


```{r cache=TRUE}
fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
cat("Unpacking the raw data file:\n")

outDir <- project.extdata             # folder for raw data
downloadZip(fileUrl, outDir = outDir, bzip2 = TRUE)   # download and unpack zip file
```



## Results

## Figures
Maximum: 03. Can use panels.

## Code
